
# Clean up temporary files.
rm -rf parsing
rm -rf project/build/demo/antlr4-demo

# Cleans files generated by ANTLR4.
cd project/demo
rm -rf generated

# Clean build directories (CMAKE).
cd ..
rm -rf build run dist


